; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "WeatherApp"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "Weather"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\WeatherApp.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "C:\Users\jf_tr\Downloads\cloud.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "WeatherApp0459325"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\WeatherApp.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "French"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Installjf0459325.exe"
InstallDir "$PROFILES\0459325"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "APP" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\WeatherApp.runtimeconfig.json"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\WeatherApp.runtimeconfig.dev.json"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\WeatherApp.deps.json"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\appsettings.json"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\WeatherApp.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\System.Net.Http.Formatting.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\OpenWeatherAPI.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Newtonsoft.Json.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Newtonsoft.Json.Bson.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Primitives.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Options.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Options.ConfigurationExtensions.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.FileSystemGlobbing.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.FileProviders.Physical.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.FileProviders.Abstractions.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.DependencyInjection.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Configuration.UserSecrets.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Configuration.Json.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Configuration.FileExtensions.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Configuration.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Configuration.Binder.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\Microsoft.Extensions.Configuration.Abstractions.dll"
  File "C:\Users\jf_tr\OneDrive\Bureau\wpf\WeatherStation_tp4b\WeatherApp\bin\Release\netcoreapp3.1\WeatherApp.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\WeatherApp.lnk" "$INSTDIR\WeatherApp.exe"
  CreateShortCut "$DESKTOP\WeatherApp.lnk" "$INSTDIR\WeatherApp.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\WeatherApp.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\WeatherApp.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) a �t� d�sinstall� avec succ�s de votre ordinateur."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "�tes-vous certains de vouloir d�sinstaller totalement $(^Name) et tous ses composants ?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\WeatherApp.exe"
  Delete "$INSTDIR\Microsoft.Extensions.Configuration.Abstractions.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Configuration.Binder.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Configuration.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Configuration.FileExtensions.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Configuration.Json.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Configuration.UserSecrets.dll"
  Delete "$INSTDIR\Microsoft.Extensions.DependencyInjection.Abstractions.dll"
  Delete "$INSTDIR\Microsoft.Extensions.DependencyInjection.dll"
  Delete "$INSTDIR\Microsoft.Extensions.FileProviders.Abstractions.dll"
  Delete "$INSTDIR\Microsoft.Extensions.FileProviders.Physical.dll"
  Delete "$INSTDIR\Microsoft.Extensions.FileSystemGlobbing.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Options.ConfigurationExtensions.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Options.dll"
  Delete "$INSTDIR\Microsoft.Extensions.Primitives.dll"
  Delete "$INSTDIR\Newtonsoft.Json.Bson.dll"
  Delete "$INSTDIR\Newtonsoft.Json.dll"
  Delete "$INSTDIR\OpenWeatherAPI.dll"
  Delete "$INSTDIR\System.Net.Http.Formatting.dll"
  Delete "$INSTDIR\WeatherApp.dll"
  Delete "$INSTDIR\appsettings.json"
  Delete "$INSTDIR\WeatherApp.deps.json"
  Delete "$INSTDIR\WeatherApp.runtimeconfig.dev.json"
  Delete "$INSTDIR\WeatherApp.runtimeconfig.json"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$DESKTOP\WeatherApp.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\WeatherApp.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd